#CONFIGURACIONES PARA QUE FUNCIONE DOCKER
version: "3.8"

services:
  mysql:
    image: mysql:8
    restart: always
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullstack
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "3001:3001"
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: fullstack
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mysql_data: